icedtea7-native: set ALT_CUPS_HEADERS_PATH to staging
ALT_CUPS_HEADERS_PATH eventually gets added to some links as
-I/usr/include

If you are using the buildtools-extended-tarball, the limits.h
from the system gets included first then later the limits.h
from the buildtools tarball gets added again, but is missing
glibc definitions, if the system glibc is much older(centos7).

This leads to:
In file included from /usr/include/limits.h:124,
                 from /usr/include/sys/param.h:26,
                 from ../../../src/solaris/javavm/export/jvm_md.h:35,
                 from ../../../src/share/javavm/export/jvm.h:32,
                 from ../../../src/solaris/native/sun/awt/awt.h:33,
                 from ../../../src/solaris/native/sun/awt/awt_p.h:75,
                 from ../../../src/solaris/native/sun/awt/awt_MToolkit.c:26:
/build/buildtools/sysroots/x86_64-montavistasdk-linux/usr/include/limits.h:145:17: error: missing binary operator before token "("
  145 | #if __GLIBC_USE (IEC_60559_BFP_EXT_C2X)

Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>